name: ci

on: [ push, pull_request ]

jobs:
  tests:
    name: unit tests
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        nvim-version: [ stable, nightly ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-version }}
      - name: Install plenary-busted plugin
        run: |
          git clone --depth=1 -b fix_paths https://github.com/monkoose/plenary-busted ~/.local/share/nvim/site/pack/test-workflow/start/plenary-busted
      - name: Run tests
        run: |
          nvim --version
          make test

  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
