local conf = require("neocodeium.utils.conf")

describe("load()", function()
   it("should return decoded json table", function()
      local data = conf.load("tests/assets/config.json")
      assert.is.Table(data)
      assert.are.Same(data, { test = true })
   end)
   it("should return empty table if file doesn't exists", function()
      assert.are.Same(conf.load("tests/assets/not_exists.json"), {})
   end)
end)
