local conf = require("neocodeium.utils.conf")

describe("dir()", function()
   it("should return correct path string", function()
      local path = conf.dir()
      assert.is.True(vim.endswith(path, "/codeium"))
   end)
end)

describe("data_dir()", function()
   it("should return correct path string", function()
      local regex = vim.regex([[/\.\?codeium$]])
      assert.is.Truthy(regex:match_str(conf.data_dir()))
   end)
end)

describe("load()", function()
   it("should return decoded json table", function()
      local data = conf.load("tests/assets")
      assert.is.Table(data)
      assert.are.Same(data, { test = true })
   end)
   it("should return empty table if file doesn't exists", function()
      assert.are.Same(conf.load("tests/assets/not_exists.json"), {})
   end)
end)
